### ISSUE TITLE
Support for streaming at input and output

### ISSUE THREAD

**Issue by splatch** [arakelian/java-jq#1]
I found a use case with java-jq in middleware and it is really great thing that this wrapper is provided.

We are running java-jq as part of mobile app proxy to compact json contents from 3rd party service and minimize transfer from mobile side.
Current interface of java-jq allows to pass String contents and this seems to be a potential bottleneck as we need to aggregate fairly big amount of data coming in chunks (10+ megs) in order to process call transformation.
Would it be possible to support input/output stream or nio's byte buffer within request/response interface?

**Comment by arakelian** [comment]
It's certainly possible from a java-jq interface perspective, but I'd need to do some research to see if JQ will accept streamed content (it appears to), and to determine what it buys you.  I thought about doing this when I first wrote the wrapper, but felt that since JQ would likely be building an in-memory DOM for the Json anyway, a large document would have to fit in RAM, and then what value is streaming really? 

I'll mark this as an enhancement, and see if I can experiment with it in the coming weeks.

**Comment by arakelian** [comment]
This is not something I plan to implement at this time. I'd accept a PR, however.
